### ISSUE TITLE
dyc start should show in what file method is

### ISSUE THREAD

**Issue by vccolombo** [Zarad1993/dyc#10]
When you run `dyc start`, the terminal shows the name of the next function/method to document. However, it does not show in what file this method is. Inside a project with multiple files, this could be misleading as functions / methods with same name may be present in multiple files and classes. Could we change the terminal command to show in what file is the function it's asking to confirm if you want to document? 
I was thinking even if there is a way to show the line where the function is in the file, this could help also.

Thank you very much

**Comment by Zarad1993** [comment]
Agreed, I used to have a print which shows the path of the file in `main.process_methods`

But that didn't look nice when you only have one method that needs docstrings over a 200 files. 

https://github.com/Zarad1993/dyc/blob/a4152655026ec158945292b5b3b5a4af14890597/dyc/main.py#L29-L43


It would be great to print the filename only if it has methods that are subject to docstrings.

Feel free to start on that!

**Comment by vccolombo** [comment]
I'll be glad to take a look on it! Give me a few days as I'm a bit busy this week

Thanks again

**Comment by vccolombo** [comment]
May I ask if in https://github.com/Zarad1993/dyc/blob/369aba4792e1c39a0e9849cde1c4ad1010e68b8e/dyc/main.py#L28 is \r necessary? If I want to remove one of the break lines in this print, should I remove \n or \r?

**Comment by Zarad1993** [comment]
@vccolombo - But it's the reference to what stage currently is running. As we have the other (class/top file) in progress. Any idea how to better reference them . An alternative is totally acceptable.
