### ISSUE TITLE
Python3 Diff failure

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#12]
When working on Python3, `dyc diff`

Docstrings tries to run on all the file and not only the patch suggested.

Try to add a couple of empty lines in `dyc/utils.py` and then run `dyc diff` on Python3.

You will be prompted to document a function
**Python3.7**
<img width="473" alt="Screen Shot 2019-05-04 at 10 47 01 AM" src="https://user-images.githubusercontent.com/18662248/57180785-306be480-6e5a-11e9-9234-c02f28a96a8c.png">
<img width="666" alt="Screen Shot 2019-05-04 at 10 47 15 AM" src="https://user-images.githubusercontent.com/18662248/57180786-306be480-6e5a-11e9-96e9-b7fcc27ddbca.png">

**Python2.7**

<img width="973" alt="Screen Shot 2019-05-04 at 10 49 15 AM" src="https://user-images.githubusercontent.com/18662248/57180804-54c7c100-6e5a-11e9-8a26-f50864a96241.png">
<img width="521" alt="Screen Shot 2019-05-04 at 10 49 26 AM" src="https://user-images.githubusercontent.com/18662248/57180805-54c7c100-6e5a-11e9-96b4-914b001281c6.png">
<img width="855" alt="Screen Shot 2019-05-04 at 10 49 33 AM" src="https://user-images.githubusercontent.com/18662248/57180806-54c7c100-6e5a-11e9-8459-745b83d9c264.png">

**Comment by Zarad1993** [comment]
@vccolombo - Have you faced similar issue?

**Comment by vccolombo** [comment]
In fact I can reproduce it. I'll take a look if I changed something that could break it in the last merge. Do you have any idea on how to fix it?

**Comment by vccolombo** [comment]
I tracked this issue until https://github.com/Zarad1993/dyc/blob/369aba4792e1c39a0e9849cde1c4ad1010e68b8e/dyc/diff.py#L29
This line returns different values in Python 3 and Python 2. I will continue to look for a solution

**Comment by Zarad1993** [comment]
Thanks for looking into that Victor, I don’t think anything broke. Just
unhandled python3 scenario, should be normal as part of the migration. We
can handle that. Feel free to submit a PR for that.

Highly appreciated!

**Comment by Zarad1993** [comment]
@vccolombo - I found the error. It's in here.

https://github.com/Zarad1993/dyc/blob/369aba4792e1c39a0e9849cde1c4ad1010e68b8e/dyc/main.py#L30-L33

After printing the error. This is the message

`TypeError("'filter' object is not subscriptable")`

Looks like it returns a generator in python 3, converting it to a list should make it work for both versions

Will have a PR up

**Comment by Zarad1993** [comment]
Fixed in this [commit](https://github.com/Zarad1993/dyc/commit/dd6c8b8f86acb6503f7678d0368c2adeb0b5adc5)
