### ISSUE TITLE
Method docstring showing for object attributes

### ISSUE THREAD

**Issue by mboekhold** [Zarad1993/dyc#13]
Currently, running dyc start not only prompts for the methods in the file, but also it's attributes, I'm not sure if this is desired, if it is go ahead and close this issue. 

Example: 
![image](https://user-images.githubusercontent.com/21144386/57240801-bc833500-702f-11e9-870d-8cd59bfd6b3d.png)

**Comment by mboekhold** [comment]
Would this be appropriate as default?

**Comment by vccolombo** [comment]
Hello @mboekhold 
I can't reproduce your problem, can you please give a step by step, python version and the code you want to document?
![dyc1](https://user-images.githubusercontent.com/19277813/57311655-6ca17e00-70c2-11e9-893a-2d2ba4ac0af7.png)

**Comment by mboekhold** [comment]
@vccolombo run `dyc start` in the project's root folder with an active virtual env, I was able to print the filenames to get make it a bit clearer. this is the result:

![image](https://user-images.githubusercontent.com/21144386/57316282-b35c9b80-70f5-11e9-947e-9eae2e938517.png)

**Comment by Zarad1993** [comment]
@mboekhold - I was also unable to reproduce that on two Virtualenvs. One on `37` and `27`
Please check the GIF below.

http://recordit.co/Xjq6MXnrEs

-------

In addition to it, just incase methods needs to be avoided. these can be added in the `ignore` key?

**Comment by mboekhold** [comment]
That's strange, any idea why I'm getting a different result? 

![](https://i.imgur.com/vWdmKJ3.gif)

**Comment by vccolombo** [comment]
Looks like you created your venv directory inside dyc folder. DYC is recursively trying to document every file from your current directory. It then enters venv directory and tries to document its methods.

> Currently, running dyc start not only prompts for the methods in the file, but also it's attributes

Are you sure about that? If you look at the file it is trying to document, I think all of them are actually methods, e.g.`def __len__(self):
                return 1 << 31` in venv/lib/python3.6/site-packages/six.py

Can you please confirm you created your venv inside dyc directory? If so, what I prefer to do is to create a directory called dyc_dev, clone dyc inside it and create the venv inside dyc_dev like so:

dyc_dev
 |
 |-- venv
 |-- dyc

**Comment by mboekhold** [comment]
Ah okay that makes sense, thank you @vccolombo
