### ISSUE TITLE
Test failing in Python 3

### ISSUE THREAD

**Issue by vccolombo** [Zarad1993/dyc#15]
The following test is failling in Python 3
![pytest_dyc](https://user-images.githubusercontent.com/19277813/57314682-83e36a00-70c8-11e9-9fb7-e070e6918def.png)

https://github.com/Zarad1993/dyc/blob/2e28794b0c994b6894d3ee0d77d633c7afa225c0/tests/test_utils.py#L55-L60
I didn't understand what this test is doing, could you please explain to me @Zarad1993 ? Thank you very much

**Comment by Zarad1993** [comment]
@vccolombo - It is ensuring that all attribute types do not raise an exception and instead returns an empty value. Just to avoid crashing. And it looks like it's missing the `TypeError` handle.

I'll have a PR up for this.
