### ISSUE TITLE
Print filename starting from project directory

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#22]
It would be better to have the printing of a file name starting from the project itself and not coming from the root of CPU

Example:
This

<img width="549" alt="Screen Shot 2019-05-09 at 2 46 37 PM" src="https://user-images.githubusercontent.com/18662248/57478652-7b766500-7269-11e9-938b-d346c89dc54c.png">

Should be

`tests/test_utils.py`

Which will end up being more readable to the end user

**Comment by felipehfs** [comment]
Hello, I'm interesting in help you. How do I test the forked project?

**Comment by mboekhold** [comment]
Hi, you can test your changes by running dyc start on test_utils.py

**Comment by mohit741** [comment]
hello @mboekhold Can I try? 
p.s New to OSS contributions

**Comment by mboekhold** [comment]
Hi @mohit741 , @felipehfs is currently working on this, but you are welcome to grab any other open issue.

**Comment by NanduTej** [comment]
Hey @mboekhold ! Is this issue still open?

**Comment by mboekhold** [comment]
I believe so, go ahead

**Comment by nils-van-zuijlen** [comment]
Was this issue fixed in #33 or not ? If it was, why is it still open ?

**Comment by mboekhold** [comment]
Not a very active repo, but i will close thanks @nils-van-zuijlen
