### ISSUE TITLE
Arguments are not well caught

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#24]
When arguments are being added in an unusual format.
Like:
```python
def hello(x=1,
               y=2,
               z=3)
```

Output

<img width="533" alt="Screen Shot 2019-05-09 at 4 59 53 PM" src="https://user-images.githubusercontent.com/18662248/57486332-e761c900-727b-11e9-933e-715217dd4317.png">

**Comment by alucardthefish** [comment]
Hi, Can I work on this issue?

**Comment by Zarad1993** [comment]
Yes please @alucardthefish

**Comment by alucardthefish** [comment]
It's ready for revision.
