### ISSUE TITLE
Add job to travis to check formatting

### ISSUE THREAD

**Issue by mboekhold** [Zarad1993/dyc#28]
It would be a good addition to let travis check that the format of a file is according to black standards.

**Comment by dmoneyballer** [comment]
What are black file format standards. I googled it and found a few references here https://en.wikipedia.org/wiki/List_of_file_formats. is it .obt files?

**Comment by mboekhold** [comment]
Hi, https://black.readthedocs.io/en/stable/ is a superset of the pep8 coding standards.
