### ISSUE TITLE
Github Hooks

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#4]
It will be great to do a sane check with `dyc diff` when trying to commit.

Maybe something like `dyc set precommit`

**Comment by ynx0** [comment]
@Zarad1993 can I try doing this?

**Comment by navyakanu** [comment]
@ynx0  are you working on this?  If not, @Zarad1993 can I pick this up?

**Comment by ynx0** [comment]
@navyakanu, I apologize for the lack of response. 
Unfortunately, I neglected to work on this issue. I would appreciate it if you could work on it, @Zarad1993.

**Comment by navyakanu** [comment]
@ynx0 , thanks for the reply, @Zarad1993 , i would like to work on this, Ill raise a PR by tomorrow

**Comment by navyakanu** [comment]
#39 I understand there can be more than one solution for this, waiting for your review comments

**Comment by Zarad1993** [comment]
Solved!
