### ISSUE TITLE
Error coming up.

### ISSUE THREAD

**Issue by seema1711** [Zarad1993/dyc#52]
ImportError: attempted relative import with no known parent package.
We can correct this by making a new folder under which all the python files will be present and in the parent folder, there will be main.py.

And, there are many errors coming up in other files too.
How can I remove them?

**Comment by Zarad1993** [comment]
Hey @seema1711 - Thank you for reporting an issue. Can you provide some more context, please? Is that happening on installation? Or setting up for contribution?

Installing the latest release `0.2.3` on Python 3.7 has no issues.

<img width="1425" alt="Screen Shot 2020-05-09 at 10 38 33 PM" src="https://user-images.githubusercontent.com/18662248/81483293-d6a8b200-9245-11ea-9c0f-bf954d384107.png">

**Comment by seema1711** [comment]
@Zarad1993 , I am not able to run main.py, maybe I am doing it wrong. The code is working fine when I use dyc start. But when I try to run any python file, it shows me an error.
