### ISSUE TITLE
Saving and exiting in Vim with ":x"

### ISSUE THREAD

**Issue by mquevill** [Zarad1993/dyc#54]
When `dyc` opens up the editor to modify the docstrings, there's some weird behavior with the Vim editor. If I save and quit with `:wq`, it exits as expected. However, if you use `:x` or `ZZ`, it exits with the error message `Quitting the program in the editor terminates the process. Thanks`, even though it should be treated as a proper save and quit. (Though I know that `:wq` and `:x` are not exactly equivalent.)

**Comment by Zarad1993** [comment]
@mquevill - Thanks for reporting this, should be good now. I'll tag a new release this weekend. 🙂
