### ISSUE TITLE
Top File Docstrings

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#7]
We have a ready method `process_top` method that is waited to be implemented.
That feature would help with documenting the top of the file.

**Comment by mboekhold** [comment]
Hey @Zarad1993 , I'd like to try and grab this one

**Comment by Zarad1993** [comment]
Sure thing! Will label `taken`

**Comment by mboekhold** [comment]
Do you have an IRC?

**Comment by mboekhold** [comment]
Can you let me know if you do, I have some questions

**Comment by Zarad1993** [comment]
@mboekhold - I'm sorry that is not available. Feel free to ask any questions in here.

**Comment by mboekhold** [comment]
Sorry, I've been busy. Can you let me know the sequence of calls that is necessary for this? I'm aware that the execution would follow similar to Method docstrings, but I have trouble navigating on what and where it's being executed. 

I guess I'm asking for a quick run down on the code process of creating method doc string as well what would be needed to do the top doc string

**Comment by mboekhold** [comment]
@Zarad1993 Can you let me know if this would be possible?

**Comment by Zarad1993** [comment]
@mboekhold - Sorry for the late answer. Honestly, I haven't tried to sketch the sequential calls required to start this. We would probably need a new `top.py` file that handles the top part of `dyc`. And then the class would be processed/executed within `process_top`.

**Comment by mboekhold** [comment]
@Zarad1993 We need to take a second look at base.py, namely at method `def initialize(self, change=None)` currently, it's not abstract enough to build top docstrings. `keywords = self.config.get('keywords')`, for top file docstrings, this not needed.

**Comment by mboekhold** [comment]
@Zarad1993 To be clearer, referring to these lines.

https://github.com/Zarad1993/dyc/blob/2c3b41236f1d2165d4bfbe536d7b8c1c0b019d45/dyc/base.py#L19-L23

**Comment by Zarad1993** [comment]
Gotcha, feel free to open an abstracting PR for the sake of implementing the top file.

**Comment by mboekhold** [comment]
I wan't to debug when I run `dyc start filename`, I'm using vscode and the current file debugging raises `attempted relative import`. Is there a way I can debug on application running cycle?

**Comment by AshirGuptash** [comment]
Is this issue still open?

**Comment by Zarad1993** [comment]
@AshirGuptash - I believe so.

**Comment by mboekhold** [comment]
There's a PR I did for this @Zarad1993  #20

**Comment by Zarad1993** [comment]
Sorry @mboekhold  🙇 , I missed that. I'll update the labels.
